"""Add game summary, igdb score and release date

Revision ID: 24b33445bde9
Revises: 17fee0611870
Create Date: 2022-04-26 05:35:47.762212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24b33445bde9'
down_revision = '17fee0611870'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('igdb_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('summary', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('release_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('release_date')
        batch_op.drop_column('summary')
        batch_op.drop_column('igdb_score')

    # ### end Alembic commands ###
