"""empty message

Revision ID: 568d46f9a52e
Revises: 831951ee168b
Create Date: 2022-04-05 09:38:43.236220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '568d46f9a52e'
down_revision = '831951ee168b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('short', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_genres')),
    sa.UniqueConstraint('slug', name=op.f('uq_genres_slug'))
    )
    op.create_table('game_genres',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_game_genres_game_id_games')),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], name=op.f('fk_game_genres_genre_id_genres')),
    sa.PrimaryKeyConstraint('game_id', 'genre_id', name=op.f('pk_game_genres'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_genres')
    op.drop_table('genres')
    # ### end Alembic commands ###
