"""empty message

Revision ID: 831951ee168b
Revises: 93c67c900f74
Create Date: 2022-04-05 08:22:31.415395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '831951ee168b'
down_revision = '93c67c900f74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('views', sa.Integer(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('views')

    # ### end Alembic commands ###
