"""Add keys table

Revision ID: 8fd3b4ae8b9c
Revises: ab5359fcdf53
Create Date: 2022-05-27 19:33:40.341774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fd3b4ae8b9c'
down_revision = 'ab5359fcdf53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keys',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('coerce', sa.Enum('INT', 'BOOL', 'FLOAT', name='types'), nullable=True),
    sa.PrimaryKeyConstraint('name', name=op.f('pk_keys'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('keys')
    # ### end Alembic commands ###
