"""empty message

Revision ID: 93c67c900f74
Revises: dde961ed3af8
Create Date: 2022-03-29 06:58:00.209388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93c67c900f74'
down_revision = 'dde961ed3af8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_platforms',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_game_platforms_game_id_games')),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], name=op.f('fk_game_platforms_platform_id_platforms')),
    sa.PrimaryKeyConstraint('game_id', 'platform_id', name=op.f('pk_game_platforms'))
    )
    op.create_table('game_tags',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_game_tags_game_id_games')),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_game_tags_tag_id_tags')),
    sa.PrimaryKeyConstraint('game_id', 'tag_id', name=op.f('pk_game_tags'))
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_reviews_author_id_users')),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_reviews_game_id_games')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews'))
    )
    op.create_table('review_tags',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], name=op.f('fk_review_tags_review_id_reviews')),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_review_tags_tag_id_tags')),
    sa.PrimaryKeyConstraint('review_id', 'tag_id', name=op.f('pk_review_tags'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_tags')
    op.drop_table('reviews')
    op.drop_table('game_tags')
    op.drop_table('game_platforms')
    # ### end Alembic commands ###
