"""empty message

Revision ID: dde961ed3af8
Revises: 0c556e157566
Create Date: 2022-03-29 06:38:51.606665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dde961ed3af8'
down_revision = '0c556e157566'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('force_icon', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('force_rating', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_column('force_rating')
        batch_op.drop_column('force_icon')

    # ### end Alembic commands ###
